"""
Django settings for raotproject project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q$@10ubp67y+hd^rqsja4&pnne$fg-yai8pf^c62#x4%2etjo6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'raotsuplementos.com.mx', 'www.raotsuplementos.com.mx']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'crispy_forms',
    'rest_framework',
    
    # Local apps
    'store',
    'cart',
    'checkout',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'raotproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add this line to point to our templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',  # Add this line
                'store.context_processors.categories',  # Add this line
            ],
        },
    },
]

WSGI_APPLICATION = 'raotproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Default to SQLite for local development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# RAOT-specific settings
RAOT_COLORS = {
    'BACKGROUND': '#000000',
    'PRIMARY': '#e12e20',
    'ACCENT': '#ffd700',
}

# Cart settings
CART_SESSION_ID = 'cart'

# CLIP.MX Payment Settings
CLIPMX = {
    'API_KEY': 'test_65ea9941-283e-4010-a2c0-a0cca5089264',
    'SECRET_KEY': 'e6973234-5e41-4c3a-af80-48b8cd43984a',
    'TOKEN': 'Basic dGVzdF82NWVhOTk0MS0yODNlLTQwMTAtYTJjMC1hMGNjYTUwODkyNjQ6ZTY5NzMyMzQtNWU0MS00YzNhLWFmODAtNDhiOGNkNDM5ODRh',
    'MODE': 'test',  # Change to 'live' in production
    'WEBHOOK_SECRET': '',  # Add your webhook secret if needed
}

# CLIP.MX Payment Gateway Settings
CLIP_API_KEY = 'f1544953-c525-470c-a912-1f65c11a57ee'
CLIP_SECRET_KEY = 'f254c93d-e7e8-41cf-ab14-a313f3c0d2b3'
CLIP_WEBHOOK_SECRET = 'f254c93d-e7e8-41cf-ab14-a313f3c0d2b3'

# Site URL - used for payment callbacks
SITE_URL = 'https://raotsuplementos.com.mx'  # Change to your actual domain

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
DEFAULT_FROM_EMAIL = 'noreply@raotsupplements.com'

# Jazzmin settings
JAZZMIN_SETTINGS = {
    # Title on the login screen
    "site_title": "RAOT Admin",
    
    # Title on the brand (19 chars max)
    "site_header": "RAOT",
    
    # Square logo to use for your site
    "site_logo": None,  # Remove the site_logo setting or set to a small icon
    "site_icon": "images/favicon.ico",  # Use a small favicon
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to RAOT Supplements Admin",
    
    # Copyright on the footer
    "copyright": "RAOT Supplements Ltd",
    
    # The model admin to search from the search bar
    "search_model": "store.Product",
    
    # Field name on user model that contains avatar image
    "user_avatar": None,
    
    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    
    # Custom icons for side menu apps/models
    "icons": {
        "store.category": "fas fa-folder",
        "store.product": "fas fa-box-open",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "cart.cart": "fas fa-shopping-cart",
        "orders.order": "fas fa-file-invoice-dollar",
    },
    
    # Theme
    "dark_mode_theme": "darkly",
    
    # UI Customizer
    "show_ui_builder": True,
    
    # Custom CSS
    "custom_css": "css/admin.css",
    
    # Custom JS
    "custom_js": "js/admin.js",
    
    # Logo to use for login form in dark theme
    "login_logo": None,  # Remove this or set to a properly sized image (max 150px height)
    
    # Logo to use for login form in light theme
    "login_logo_dark": None,  # Remove this or set to a properly sized image
    
    # Custom links at the footer of the sidebar menu
    "custom_links": {
        "store": [{
            "name": "Product Stats", 
            "url": "admin:index", 
            "icon": "fas fa-chart-line",
        }],
    },
    
    # Show charts on the dashboard
    "show_chart": True,
    
    # Dashboard configuration
    "dashboard_charts": [
        {
            "type": "bar",
            "title": "Product Sales",
            "model": "store.Product",
            "dimension": "name",  # Assuming you add a sales field later
        },
    ],
    
    # Additional dashboard widgets
    "dashboard_widgets": [
        "store.models.RecentProductsWidget",  # You can create this later
        "auth.models.UserCountWidget",
        {
            "type": "recent_actions",
            "limit": 10,
            "title": "Recent Admin Actions",
        },
    ],
}

# UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-danger",  # Red theme to match RAOT color
    "accent": "accent-danger",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-danger",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "superhero",
    "dark_mode_theme": "superhero",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Make sure this is at the BOTTOM of your settings.py file:

# Import local settings if available, otherwise use SQLite for development
try:
    from .settings_local import *
except ImportError:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
